### ISSUE TITLE
HTTPSignatureAuth.verify does not parse Authentication header correctly

### ISSUE THREAD

**Issue by Diggsey** [pyauth/requests-http-signature#11]
Currently, it just splits on commas. However, I believe commas are allowed in eg. the `keyId` parameter if the value is enclosed in quotes.

Example:
```
Authentication: keyId="test,key",signature="...",algorithm="..."
```

**Comment by kislyuk** [comment]
No, keyId should not contain commas. There is an in-progress work item on this in the draft spec (https://tools.ietf.org/html/draft-richanna-http-message-signatures-00#appendix-B.1.13).
