### ISSUE TITLE
Add HTTPSignatureHeaderAuth.verify()

### ISSUE THREAD

**Issue by sharpaper** [pyauth/requests-http-signature#19]
The class `HTTPSignatureHeaderAuth` inherits the method `verify()` that uses the default `scheme="Authorization"`. It would be nice to override this method such that `scheme="Signature"` is set automatically:

    class HTTPSignatureHeaderAuth(HTTPSignatureAuth):
        def verify(self, request, key_resolver):
            return super().verify(request, key_resolver, scheme="Signature")

**Comment by georgkrause** [comment]
I just put this into a Merge Request, linked above. Please feel free to review and add any comments. Thanks for the suggestions.

**Comment by kislyuk** [comment]
This is no longer an issue in the latest implementation, which uses only the "Signature-Input"/"Signature" scheme as described in the most recent draft.
