### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sharpaper** [pyauth/requests-http-signature#20]
Hi, and thank you for working on this library.
I was wondering, since the current release on pypi is 0.1.0 (from 2018), if it was possible to publish even a minor release update in order to get the package on pypi up to date with the last changes. Thank you.

**Comment by epicfaace** [comment]
@kislyuk any idea on the timeline for this?

**Comment by kislyuk** [comment]
Released v0.2.0, please test.

**Comment by kislyuk** [comment]
(The delay in releasing was due to some unfinished updates that I have in progress to match the most recent RFCs. Since I won't have time to finish those until a bit later, I am releasing the contributions made since the last release in v0.2.0 so people can use those.)

**Comment by epicfaace** [comment]
Great, thanks @kislyuk ! Appreciate it 🙂
