### ISSUE TITLE
Support httpx

### ISSUE THREAD

**Issue by max-tet** [pyauth/requests-http-signature#37]
[HTTPX](https://github.com/encode/httpx/) tries to be compatible with the requests package, including the use of callables for custom authentication. However, it is incompatible with requests_http_signature. When trying to sign a request, this is the error: `AttributeError: 'Request' object has no attribute 'body'`

requests_http_signature expects the `body` attribute [here](https://github.com/pyauth/requests-http-signature/blob/develop/requests_http_signature/__init__.py#L129), but the [Request](https://www.python-httpx.org/api/#request) object does not have the attribute because it is called `content`.

What I don't understand is that the [Request object of the Requests library](https://requests.readthedocs.io/en/latest/api/#requests.Request) also seems to have no attribute called `body`. Why does it work here then?

**Comment by kislyuk** [comment]
Thanks, I'll take a look at making this package compatible with httpx. The first step would be to write a test case.

The reason you're not seeing `body` is that it's an attribute of PreparedRequest, not Request. The auth helper plugin operates on PreparedRequest.

**Comment by kislyuk** [comment]
(Reference: https://requests.readthedocs.io/en/latest/api/#requests.PreparedRequest)

**Comment by max-tet** [comment]
Right, thanks for the clarification. AFAIK, httpx has no notion of a prepared request. But I guess that should not be a problem.

**Comment by kislyuk** [comment]
It looks like the httpx auth protocol is substantially different and will require a new package. Supporting httpx is outside the scope of this package, but can be accommodated by a new package in the pyauth project.

https://github.com/encode/httpx/blob/master/httpx/_auth.py

**Comment by max-tet** [comment]
Thanks for looking into that. So httpx and Requests are not as compatible as advertised. I'll get back to using Requests then for the moment.
