### ISSUE TITLE
default code example key > value not byte array

### ISSUE THREAD

**Issue by robcordes** [pyauth/requests-http-signature#5]
TypeError: key: expected bytes or bytearray, but got 'str'

**Comment by clauney** [comment]
I found the same. MacOS, python 3.7. Py37's hmac raises TypeError if the key isn't bytes or bytesarray. Simply encoding the key didn't seem to work, though I'm not sure, as I don't have a reference "good" call for this httpsig api to compare.

**Comment by kislyuk** [comment]
Thanks for reporting, this is now fixed.

**Comment by clauney** [comment]
Thank you!
