### ISSUE TITLE
Asymmetric key full example

### ISSUE THREAD

**Issue by sharpaper** [pyauth/requests-http-signature#6]
Hi, thanks a lot for writing this library. I'm trying to setup HTTP signatures using RSA but I'm struggling to get it working. Could you please add an example of `key_resolver()` with RSA in the README?
Thank you!

**Comment by sharpaper** [comment]
Is verification for HTTPSignatureHeaderAuth actually implemented? Reading the source code, it looks like only the validation of `Authorization: ` headers is there.

**Comment by sharpaper** [comment]
Related to: https://github.com/pyauth/requests-http-signature/pull/4/files

**Comment by kislyuk** [comment]
Thanks for your interest in requests-http-signature and apologies for the belated response here. The support for signature headers and asymmetric key algorithms has been largely rewritten, so please take a look at the latest release and its documentation, and let me know if this is still a problem.
