### ISSUE TITLE
Cannot verify "host" with HTTPSignatureAuth

### ISSUE THREAD

**Issue by sharpaper** [pyauth/requests-http-signature#7]
When using `host` in `headers=` with HTTPSignatureAuth, the signature does not validate.

Example:

- **makes valid signature:** `headers=[ '(request-target)', 'date', 'digest' ]`
- **makes not valid signature:** `headers=[ '(request-target)', 'host', 'date', 'digest' ]`

I cannot test `HTTPSignatureHeaderAuth` because there is not `verify` method available.

**Comment by kislyuk** [comment]
Thank you for submitting your bug report. I am unable to reproduce the issue that you described. If you want further assistance, please post a complete minimal test case that reproduces the problem that you encountered.
