### ISSUE TITLE
Python's assert can be disabled

### ISSUE THREAD

**Issue by calvin620707** [pyauth/requests-http-signature#8]
https://stackoverflow.com/questions/1273211/disable-assertions-in-python

I can help to send an MR to remove assert and replaced with raising exception if it makes sense to remove assert for verification.

**Comment by kislyuk** [comment]
Thanks for pointing this out. My general suggestion for this type of issue is to not disable assertions.

PRs are welcome.

**Comment by patok** [comment]
👍 

See Dan Bader's tutorial https://dbader.org/blog/python-assert-tutorial , in caveat nr 1 he states :

> Caveat #1 – Don’t Use Asserts for Data Validation
Asserts can be turned off globally in the Python interpreter. Don’t rely on assert expressions to be executed for data validation or data processing.

**Comment by kislyuk** [comment]
The latest implementation does not use assert statements for verification.
