### ISSUE TITLE
HTTPSignatureAuth.verify does not support required headers

### ISSUE THREAD

**Issue by Diggsey** [pyauth/requests-http-signature#9]
There's currently no way to require that certain headers are present in the signature, which is something all users should be doing to prevent clients from sending requests without *any* headers included in the signature.

**Comment by kislyuk** [comment]
In v0.4.0, I released functionality required to specify required components to HTTPSignatureAuth.verify:
```
HTTPSignatureAuth.verify(request, signature_algorithm=..., key_resolver=..., require_components=("foo", "bar"))
```
